apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket-server
  template:
    metadata:
      labels:
        app: websocket-server
    spec:
      containers:
        - image: websocket-server
          name: websocket-server
          imagePullPolicy: Never
          ports:
            - containerPort: 12345