apiVersion: v1
kind: Service
metadata:
  name: websocker-service
spec:
  selector:
    app: websocket-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 12345
      nodePort: 30330